
services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: dockerfile
    container_name: backend_container
    ports:
      - "8000:3000"
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev