
services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: dockerfile
    container_name: backend_container
    ports:
      - "3000:3000"
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

